# **<span style="color:#003300;">Marco Conceptual </span>** {#marco-conceptual}

---

El dengue es un problema de salud pública en los grandes centros urbanos y son objeto de gran demanda social entre la población y en ocaciones se vuelve un problema con tintes politicos. Por problemas de dengue han corrido a gobernadores y presidentes municipales, pero también han servido como bandera politica a gobernadores y secretarios de salud.

Todos los programas de salud pública tiene paradigmas altamente dominantes en los programas que adoctrinan a las instituciones, líderes de los programas, personal técnico-operativo y población general, límitando la visualización de diferentes enfoques novedosos e inovadores de prevención y control.

En el caso partícular del programa de prevención y control del dengue, las intituciones, los líderes de los programas y la población en general fue educada con la idea (a lo largo del tiempo) que las fumigaciones (nebulización) masivas o universales (toda la ciudad) eran el dogma central del programa de prevención y control del dengue. Actualmente existe evidencia que en las ciudades existen áreas donde la transmisión del dengue se concentra (hotspots) y donde los limitados recursos financieros podrían tener mayor impacto. De acuerdo a la ley de pareto 20:80, teóricamente sí en el 20% del área concentra el 80% de la transmisión, el control con intervenciones efectivas del 20% del área tendra, un 80% de reducción en la carga de la enfermedad. La evidencia científica de la existencia de los hotspots en las áreas urbanas y el razonamiento teórico de la ley de pareto, justifican un cambio de paradigma en el programa de prevención y control del dengue (y arbovirosis) de un control universal o másivo a un contro altamete focalizado.

En el caso de la comisión de riesgos sanitarios y el control de plagas, se ha institucionalizado que las controladoras de plagas son la únicas que pueden proporcionar el servicio de control de plagas y en ocaciones los dueños de los establecimientos solicitan expresamente que las compañias controladoras de plagas extiendan la constancia de fumigación sin realizar el servicios. Este paradigma y sus consecuencias, abren la puerta para visualizar los mecanismos para que los municipios articulen tres problemáticas (1) límitados recursos en salud pública, deficit financiero, y limitada recaudación de impuestos; 2) control de plagas exclusivo de controladores de plagas y corrupción, y acciones de prevención y control de sitios públicos en las áreas hotspots), y una solución integral a tres problemas añejos. La solución y cambio de paradigma sería, realizar control focalizado en las áreas hotspots en los sitios publicos y establecimientos como restaurantes y hoteles.
