# **<span style="color:#003300;">Diagnóstico</span>** {#dianostico}

---

## Antecendentes


## Situación Actual y Problemática

La situación actual y la problemática de Chilpancingo de los Bravo se divide en tres categorías para fines expositivos.

**Administración**. La administración pública del municipio de Chilpancingo de los Bravos (2021-2024) se enfrenta a un deficit de recursos de cerca de mil millones de pesos, y la proyección de las consecuencias permite visualizar que los programas prioritarios de salud pública a lo sumo operarían con el minimo basal de los recursos financieros, desproteguiendo areas sustantivas e importantes como es la prevención y control de las enfermedades transmitidas por vectores, enfermedades zoonóticas e intoxicaciones por picadura de alacrán y picadura de araña (violinista y viuda negra). 


**Verificación Sanitarias y corrupción**



**Progama de Prevención y Control del Dengue**

La presencia del dengue en el Municipios de Chilpancingo de los Bravo está documentada en bases de datos de los cubos dinamicos del SUIVE, desde finales de los 90s (1999). Sin embargo se sospecha la introducción en las costas del pacífico de los virus del dengue desde los 80s.

En el transcurso de las dos decadas de transmisión de dengue en el municipio de chilpancingo de los Bravo, el municipio se ha vuelto endémico e hiperéndemico (Figura 1 y 2). En la Figura 1 se puede observar que la transmisión continua de dengue en todos los 22 años graficados (eje x).




```{r,echo = FALSE,fig.cap = "Casos de dengue en municipio de Chilpancingo de los Bravo en el periódo comprendido entre el año 2000 al año 2021. Fuente: Cubos Dinamicos de la Dirección General de Información en Salud."}
# Step 1. load the dengue dataset #####
load("C:/Users/felip/OneDrive/proyects/12_guerrero/029_chilpancingo/test_control_fauna_nociva/8.RData/denv_12_guerrero_2000_2021.RData")
library(ggplot2)
library(gganimate)
x <- denv |>
    dplyr::filter(Municipio == "029 Chilpancingo De Los Bravo")
names(x)[c(3,4)] <- c("year", "n")
x$year <- as.numeric(x$year)
x$n_text <- as.character(x$n)

# Step 2. animates plot ####
ggplot2::ggplot(data = x,
                ggplot2::aes(x = year, 
                             y = n,
                             label = n_text)) +
    ggplot2::geom_col(col = "#003300", size = 1.5, 
                      fill = "gray50") +
    ggplot2::geom_line(col = "#330019", size = 1.5) +
    ggplot2::geom_point(col = "#003300", 
                        size = 5, shape = 21, 
                        fill = "gray50",
                        stroke = 3) +
    ggplot2::geom_text(hjust = -1, col = "#330019", size = 5) +
    #ggplot2::geom_point() +
    viridis::scale_color_viridis(discrete = TRUE) +
    ggplot2::ylab("Número de Casos de Dengue") +
    ggplot2::scale_x_continuous(breaks = c(seq(from = 2000, 
                                             to = 2021, 
                                             by = 2)))+
    gganimate::transition_reveal(year)

```


### Recursos financieros


## Avances

## Retos 2021-2024
