# **<span style="color:#003300;">Alineación de Metas </span>** {#alineacion-metas}

---

## Alineación con la leyes de Salud nacionales y estatales.

El Control de la Fauna Nociva e Insectos Transmisores de Enfermedades en Sitios Públicos se víncula con la [**La Ley General de Salud**](http://www.diputados.gob.mx/LeyesBiblio/pdf_mov/Ley_General_de_Salud.pdf) y [**Ley Número 1212 de Salud del estado de Guerrero**](http://i.guerrero.gob.mx/uploads/2013/02/L1212SEG-5.pdf) donde ambas leyes específican que **la destrucción o control de insectos u otra fauna transmisora y nociva constituyen medidas de seguridad sanitaria**


El Control de la Fauna Nociva e Insectos Transmisores de Enfermedades en Sitios Públicos está alineado con La [**La Ley General de Salud**](http://www.diputados.gob.mx/LeyesBiblio/pdf_mov/Ley_General_de_Salud.pdf), donde se señala puntualmente que **Las autoridades sanitarias competentes ejecutarán las medidas necesarias para la destrucción o control de insectos u otra fauna transmisora y nociva, cuando éstos constituyan un peligro grave para la salud de las personas** y con la [**Ley Número 1212 de Salud del estado de Guerrero**](http://i.guerrero.gob.mx/uploads/2013/02/L1212SEG-5.pdf) donde señala lo siguiente **El organismo y los Ayuntamientos en el ámbito de su respectiva competencia, ejecutarán las medidas para la destrucción o control de insectos u otra fauna transmisora y nociva, cuando éstos constituyan un peligro grave para la salud de las personas**.

## Alineación con reglamentos sanitarios


El Control de la Fauna Nociva e Insectos Transmisores de Enfermedades en Sitios Públicos se vincula con el **Artículo 1346** del [**Reglamento de la Ley General de Salud en Materia de Control Sanitario de Actividades, Establecimientos, Productos y Servicios**](http://www.diputados.gob.mx/LeyesBiblio/regley/Reg_LGS_MCSAEPS_281204.pdf) donde afirma que **La Secretaría promoverá y realizará acciones preventivas y de control de la fauna nociva que afecte a la salud pública**.
