# **<span style="color:#003300;">Organización del Programa </span>** {#organizacion-programa}

---

## **Objetivos**

### **Objetivo General**

#### El Control de la Fauna Nociva e Insectos Transmisores de Enfermedades en Sitios Públicos

### **Objetivos Específicos**

#### Realizar el control químico para el control de *Aedes aegypti*, mosquitos urbanos, garrapatas, cucarachas, garrapatas, pulgas, hormigas, y moscas en sitios públicos en los hotspots del área urbana de la cabecera municipal de Chilpancingo de los Bravo.

#### Realizar el control químico integral de roedores en sitios públicos en los hotspots del área urbana de la cabecera municipal de Chilpancingo de los Bravo.


## **Estrategias**

### **Estrategia 1**. Generar y actualizar el patrón de sitios públicos del municipio de Chilpancingo de los Bravo.

#### **Líneas de Acción**

##### Actualizar el catálogo de sitios públicos del municipio de Chilpancingo de los Bravo.

##### Construir un sistema de información geográfica de los sitios públicos del municipio de Chilpancingo de los Bravo.


### **Estrategia 2**. Generar y actualizar el patrón de las empresas controladoras de plagas del municipio de Chilpancingo de los Bravo.

#### **Líneas de Acción**

##### Actualizar el catálogo de las empresas controladoras de plagas del municipio de Chilpancingo de los Bravo.

##### Aplicar una encuesta sobre uso y aplicación de insecticidas al personal de las empresas controladoras de plagas del municipio de Chilpancingo de los Bravo.

##### Realizar una programa de educación continua sobre uso y aplicación de insecticidas en salud pública dirigido al personal de las empresas controladoras de plagas del municipio de Chilpancingo de los Bravo.

##### Construir un sistema de información geográfica de las empresas controladoras de plagas del municipio de Chilpancingo de los Bravo.

### **Estrategía 3**. Identificar los hotspots de la transmisión de dengue en el área urbana de la cabecera municipal de Chilpancingo de los Bravo.

#### **Líneas de Acción**

##### Realizar el análisis espacial para identificar los hotspots de la transmisión de dengue en el área urbana de la cabecera municipal de Chilpancingo de los Bravo.


##### Identificar sitios públicos dentro del área hotspots del municipio de Chilpancingo de los Bravo.


### **Estrategia 4**. Realizar el control integral de la fauna nociva y insectos transmisores de enfermedades.

#### **Líneas de Acción**

##### Aplicar rociado residual en sitios públicos del municipio de Chilpancingo de los Bravo.

##### Aplicar nebulización en frio en sitios públicos del municipio de Chilpancingo de los Bravo.

##### Instalar trampas de roedores en sitios públicos del municipio de Chilpancingo de los Bravo.

##### Instalar trampas pegajosas en sitios públicos del municipio de Chilpancingo de los Bravo.

##### Instalar trampas de luz en sitios públicos del municipio de Chilpancingo de los Bravo.


### **Estrategia 5**. Evaluar la efectividad del control de plagas en los sitios públicos del municipio de Chilpancingo de los Bravo.

#### **Líneas de Acción**

##### Certificar a los sitios públicos del municipio de Chilpancingo de los Bravo como áreas limpias y libres de larvas y adultos del vector del dengue.

##### Realizar el monitoreo entomológico de dipteros de importancia médica en los sitios públicos del municipio de Chilpancingo de los Bravo.

##### Realizar el monitoreo roedores en los sitios públicos del municipio de Chilpancingo de los Bravo.

##### Realizar pruebas biológicas de pared en los sitios públicos del municipio de Chilpancingo de los Bravo.

##### Realizar pruebas biológicas de jaulas en los sitios públicos del municipio de Chilpancingo de los Bravo.








